// Generated by Wrangler by running `wrangler types --env-interface=GeneratedEnv @types/generated.d.ts`

interface GeneratedEnv {
	ENVIRONMENT: "development" | "production" | "testing";
	SENTRY_DSN: "https://xxx@xxx.ingest.us.sentry.io/xxx";
}
